## Import necessary libraries

In [1]:
# general libraries
import numpy as np

## Dagger Operation

In [58]:
def dagger(A):
    return np.conj(A).T

## Generate the Observable Operators $T$

In [8]:
def observable_T(A, B, y):
    diag_B = np.diag(B[y])
    return A @ diag_B

## Generate the Kraus Operators

In [68]:
def kraus_operators(A, B):
    n = A.shape[0]
    s = B.shape[0]
    T = {}
    for i in range(s):
        T_i = observable_T(A, B, i)
        for j in range(n):
            sqrt_T_i = np.zeros(T_i.shape)
            sqrt_T_i[:,j] += np.sqrt(T_i[:,j])
            T[j,i] = sqrt_T_i
    return T

## Sample

In [69]:
A = np.array([
#FR  R    C    S
    [0.5, 0.4, 0.0], # R
    [0.3, 0.2, 0.3], # C
    [0.2, 0.4, 0.7]  # S
                     # TO
])
B = np.array([
#FR  R    C    S
    [0.8, 0.4, 0.1], # :)
    [0.2, 0.6, 0.9]  # :(
                     # Observed
])

In [70]:
n = A.shape[0]
s = B.shape[0]

T = kraus_operators(A,B)

sum_i_j = []
for i in range(n):
    sum_j = []
    for j in range(s):
        if j == 0:
            sum_j = dagger(T[i, j]) @ T[i, j]
        else:
            sum_j += dagger(T[i, j]) @ T[i, j]
    print(sum_j)
    print()
    if i == 0:
        sum_i_j = sum_j.copy()
    else:
        sum_i_j += sum_j

print("FINAL")
print(sum_i_j)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]

FINAL
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


This proves that the generated matrices are Kraus operators.